# -*- coding: utf-8 -*-
"""Aplicación de Conceptos de POO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rtYAKc2O-lrXI54Wfvk__1TETTNQRunt
"""

# Clase: Animal (Demuestra el concepto de encapsulación estricta)
class Animal:
    def __init__(self, name, sound):
        # Encapsulación estricta: '__name' y '__sound' son atributos "privados" (mediante Name Mangling).
        # Esto significa que su acceso y modificación están forzados a ser a través de los métodos.
        self.__name = name
        self.__sound = sound

    # Getter para '__name': Permite obtener el valor del nombre de forma controlada.
    def get_name(self):
        return self.__name

    # Setter para '__name': Permite modificar el nombre, incluyendo lógica de validación.
    def set_name(self, new_name):
        if isinstance(new_name, str) and new_name.strip():
            print(f"Cambiando el nombre de '{self.__name}' a '{new_name}'.")
            self.__name = new_name
        else:
            print("¡Error! El nuevo nombre no es válido o está vacío.") # Se añadió el paréntesis de cierre aquí.

    # Método que utiliza los atributos encapsulados para una acción.
    def speak(self):
        return f"{self.__name} emite un {self.__sound}"


# --- Demostración de Encapsulación Estricta ---

# Creación de una instancia de la clase Animal.
animal = Animal("León", "Rugido")
print(f"Animal inicial: {animal.get_name()}") # Acceso al nombre a través del getter.

# Uso de un método que interactúa con los atributos encapsulados.
print(animal.speak())

# Modificación del nombre utilizando el método setter.
animal.set_name("Simba")
print(f"Animal después de set_name(): {animal.get_name()}")
print(animal.speak())

# Intentos de establecer nombres inválidos para demostrar la validación del setter.
animal.set_name("") # Intento de establecer un nombre vacío.
animal.set_name(123) # Intento de establecer un nombre que no es string.
print(f"Animal después de intentos inválidos: {animal.get_name()}") # El nombre permanece inalterado.